### ISSUE TITLE
見積もりをきちんと行いたい

### ISSUE THREAD

**Issue by hajimism** [Tanden-Garage/Hoku-Navi-Beta#99]
## 🎉 Goal

- S, M, Lの大体の見積もりではなく、数字を使った厳密な見積もりを試みる体制ができあがっている
- 週次で「消化可能サイズ」を予測・観測し、見積もりの正確性をだんだんと上げていく準備ができている
- その上で、既存のチケットの見積もりが一通りできており、マイルストーンの設定と噛み合っている

## 💪 Motivation

- 時間を注げばいくらでもできてしまうが、目指すのはそこではない
- 注ぐ時間を自律的に決め、その時間内でやることをきちっと終わらせる習慣をつける
- 見積もりを出すためにTask Childrenを厳密に書いていく習慣形成にもつながる

## 📖 Reference (optional)

- [バーンダウンチャート](https://zenn.dev/rgbkids/articles/91be903ef2439c#%E3%83%90%E3%83%BC%E3%83%B3%E3%83%80%E3%82%A6%E3%83%B3%E3%83%81%E3%83%A3%E3%83%BC%E3%83%88)

## 📎 Task children

- [x] ProjectのSizeカラムを、S/M/Lからフィボナッチ数(1/2/3/5/8)に変える
- [x] 基準となる数字を決め、その数字に当てはまるチケットを１つ見つける
- [x] そのチケットを基準に、すべてのチケットにSizeを当てはめていく
- [x] 1週間で消化できる合計サイズを割り出す。また、定例会のレジュメにも、「今週消化できたサイズ・予測との乖離・その要因」「今週消化できそうなサイズ・遂行するIssue」を書けるようにテンプレートを変更する。
- [x] マイルストーンごとに全チケットの合計サイズを計算し、全てを片付けるのに何週間かかるのかを予測する
